
services:
  - type: web
    name: n8n-agroseguro
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GENERIC_TIMEZONE
        value: America/Sao_Paulo
      - key: WEBHOOK_URL
        value: https://n8n-agroseguro.onrender.com/
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
